//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(void);
int32_t checkPassword(int32_t a1);
int32_t checkRes(int32_t a1);
int32_t deregister_tm_clones(void);
int32_t format(int32_t a1, int32_t * a2);
int32_t frame_dummy(void);
int32_t function_1002(void);
int32_t function_1040(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t function_1050(int32_t a1);
int32_t function_1060(void);
int32_t function_1070(int32_t a1);
int32_t function_1080(void);
int32_t function_1090(int32_t a1);
int32_t function_10a0(int32_t a1);
int32_t function_10b0(void);
int32_t function_10c0(int32_t a1, int32_t a2);
int32_t function_10d0(int32_t a1);
int32_t function_10e0(int32_t a1);
int32_t function_10f2(void);
int32_t function_111c(int32_t a1, int32_t * a2, int32_t a3);
int32_t function_11c2(void);
int32_t function_1212(void);
int32_t function_17ca(void);
int32_t prepare(int32_t a1, int32_t * a2);
int32_t process(int32_t a1, int32_t * a2, int32_t * a3);
int32_t register_tm_clones(void);
int32_t verify(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int32_t _init(void) {
    // 0x1000
    int32_t result; // 0x1000
    return result;
}

// Address range: 0x1002 - 0x1024
int32_t function_1002(void) {
    // 0x1002
    int16_t v1; // 0x1002
    __asm_sti(v1);
    int32_t v2; // 0x1002
    __x86_get_pc_thunk_bx(v2);
    return *(int32_t *)(v2 + 0x2fdf);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0x1040
    int32_t result; // 0x1040
    return result;
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t a1) {
    // 0x1050
    int32_t result; // 0x1050
    return result;
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(void) {
    // 0x1060
    int32_t result; // 0x1060
    return result;
}

// Address range: 0x1070 - 0x1076
int32_t function_1070(int32_t a1) {
    // 0x1070
    int32_t result; // 0x1070
    return result;
}

// Address range: 0x1080 - 0x1086
int32_t function_1080(void) {
    // 0x1080
    int32_t result; // 0x1080
    return result;
}

// Address range: 0x1090 - 0x1096
int32_t function_1090(int32_t a1) {
    // 0x1090
    int32_t result; // 0x1090
    return result;
}

// Address range: 0x10a0 - 0x10a6
int32_t function_10a0(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10b6
int32_t function_10b0(void) {
    // 0x10b0
    int32_t result; // 0x10b0
    return result;
}

// Address range: 0x10c0 - 0x10c6
int32_t function_10c0(int32_t a1, int32_t a2) {
    // 0x10c0
    int32_t result; // 0x10c0
    return result;
}

// Address range: 0x10d0 - 0x10d6
int32_t function_10d0(int32_t a1) {
    // 0x10d0
    int32_t result; // 0x10d0
    return result;
}

// Address range: 0x10e0 - 0x10e6
int32_t function_10e0(int32_t a1) {
    // 0x10e0
    int32_t result; // 0x10e0
    return result;
}

// Address range: 0x10f0 - 0x10f1
int32_t _start(void) {
    // 0x10f0
    int32_t result; // 0x10f0
    return result;
}

// Address range: 0x10f2 - 0x111c
int32_t function_10f2(void) {
    // 0x10f2
    int16_t v1; // 0x10f2
    int32_t v2 = __asm_sti(v1); // 0x10f3
    int32_t v3 = v2; // bp-4, 0x10fc
    int32_t v4; // 0x10f2
    function_111c(v4, &v3, v2);
    int32_t v5; // 0x10f2
    int32_t v6; // 0x10f2
    function_1040(*(int32_t *)(v6 + 0x2ef4), (int32_t)v1, &v5, 0, 0);
    return __asm_hlt();
}

// Address range: 0x111c - 0x1120
int32_t function_111c(int32_t a1, int32_t * a2, int32_t a3) {
    // 0x111c
    int32_t result; // 0x111c
    return result;
}

// Address range: 0x1120 - 0x1124
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x1120
    int32_t result; // 0x1120
    return result;
}

// Address range: 0x1130 - 0x1169
int32_t deregister_tm_clones(void) {
    // 0x1130
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x1130
    return v1 + 0x2ed3;
}

// Address range: 0x1170 - 0x11b7
int32_t register_tm_clones(void) {
    // 0x1170
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x11c0 - 0x11c1
int32_t __do_global_dtors_aux(void) {
    // 0x11c0
    int32_t result; // 0x11c0
    return result;
}

// Address range: 0x11c2 - 0x120b
int32_t function_11c2(void) {
    // 0x11c2
    int16_t v1; // 0x11c2
    __asm_sti(v1);
    int32_t v2; // 0x11c2
    int32_t result = __x86_get_pc_thunk_bx(v2); // 0x11c8
    char * v3 = (char *)(v2 + 0x2e3b); // 0x11d6
    if (*v3 != 0) {
        // 0x1206
        return result;
    }
    // 0x11df
    if (*(int32_t *)(v2 + 0x2e1b) != 0) {
        // 0x11e9
        function_10e0(*(int32_t *)(v2 + 0x2e37));
    }
    int32_t result2 = deregister_tm_clones(); // 0x11fa
    *v3 = 1;
    // 0x1206
    return result2;
}

// Address range: 0x1210 - 0x1211
int32_t frame_dummy(void) {
    // 0x1210
    int32_t result; // 0x1210
    return result;
}

// Address range: 0x1212 - 0x1219
int32_t function_1212(void) {
    // 0x1212
    int16_t v1; // 0x1212
    __asm_sti(v1);
    return register_tm_clones();
}

// Address range: 0x1219 - 0x121d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1219
    int32_t result; // 0x1219
    return result;
}

// Address range: 0x121d - 0x12ca
int32_t process(int32_t a1, int32_t * a2, int32_t * a3) {
    // 0x121d
    int32_t v1; // 0x121d
    __x86_get_pc_thunk_ax(v1);
    int32_t v2 = function_10a0(120); // 0x123c
    *a2 = v2;
    *(int32_t *)v2 = 0;
    int32_t v3 = 1; // 0x1267
    *(int32_t *)(4 * v3 + *a2) = 0;
    v3++;
    int32_t v4 = 0; // 0x126f
    while (v3 != 30) {
        // 0x1254
        *(int32_t *)(4 * v3 + *a2) = 0;
        v3++;
        v4 = 0;
    }
    int32_t v5 = 4 * v4; // 0x12a7
    int32_t * v6 = (int32_t *)(v5 + a1); // 0x12b3
    int32_t v7 = *v6; // 0x12b3
    int32_t result = v7; // 0x12b7
    int32_t v8; // 0x129f
    int32_t * v9; // 0x1287
    if (v7 != 0) {
        v9 = (int32_t *)(*a2 + v5);
        *v9 = *v9 + 1;
        v8 = *v6 - 1;
        *v6 = v8;
        result = v8;
        while (v8 != 0) {
            // 0x127a
            v9 = (int32_t *)(*a2 + v5);
            *v9 = *v9 + 1;
            v8 = *v6 - 1;
            *v6 = v8;
            result = v8;
        }
    }
    int32_t v10 = v4 + 1; // 0x12b9
    v4 = v10;
    while (v10 != 30) {
        // 0x12a4
        v5 = 4 * v4;
        v6 = (int32_t *)(v5 + a1);
        v7 = *v6;
        result = v7;
        if (v7 != 0) {
            v9 = (int32_t *)(*a2 + v5);
            *v9 = *v9 + 1;
            v8 = *v6 - 1;
            *v6 = v8;
            result = v8;
            while (v8 != 0) {
                // 0x127a
                v9 = (int32_t *)(*a2 + v5);
                *v9 = *v9 + 1;
                v8 = *v6 - 1;
                *v6 = v8;
                result = v8;
            }
        }
        // 0x12b9
        v10 = v4 + 1;
        v4 = v10;
    }
    // 0x12c3
    return result;
}

// Address range: 0x12ca - 0x1326
int32_t verify(int32_t a1) {
    // 0x12ca
    int32_t v1; // 0x12ca
    __x86_get_pc_thunk_ax(v1);
    int32_t v2 = 5;
    for (int32_t i = 0; i < 25; i++) {
        uint32_t v3 = v2;
        char v4 = *(char *)(i + a1); // 0x12f9
        v2 = v4 != 45 ? v3 : v3 % 4;
    }
    // 0x1312
    return v2 != 92;
}

// Address range: 0x1326 - 0x13ab
int32_t format(int32_t a1, int32_t * a2) {
    // 0x1326
    int32_t v1; // 0x1326
    __x86_get_pc_thunk_bx(v1);
    int32_t v2 = function_10a0(120); // 0x1345
    for (int32_t i = 0; i < 30; i++) {
        int32_t * v3 = (int32_t *)(*a2 + 4 * i); // 0x1374
        *v3 = (int32_t)*(char *)(i + a1) << *v3 % 32;
    }
    // 0x1395
    return function_1070(v2);
}

// Address range: 0x13ab - 0x14b8
int32_t prepare(int32_t a1, int32_t * a2) {
    // 0x13ab
    int32_t v1; // 0x13ab
    __x86_get_pc_thunk_bx(v1);
    int32_t v2 = function_10c0(v1 + 3179, v1 + 3177); // 0x13d5
    int32_t v3; // bp-28, 0x13ab
    int32_t v4 = &v3; // 0x13da
    int32_t v5 = 0; // 0x14a3
    char v6 = *(char *)(v5 + a1); // 0x13f4
    uint32_t v7 = (int32_t)v6 - 99; // 0x13fa
    while (v6 != 125 && v7 >= 26) {
        // 0x148c
        *(int32_t *)(v4 - 4) = v2;
        *(int32_t *)(v4 - 8) = 5;
        *(int32_t *)(v4 - 12) = 1;
        *(int32_t *)(v4 - 16) = v1 + 3222;
        int32_t result = function_1090(v5); // 0x149a
        v5++;
        if (v5 >= 30) {
            // 0x14b1
            return result;
        }
        v6 = *(char *)(v5 + a1);
        v7 = (int32_t)v6 - 99;
    }
    // 0x1406
    return v1 + 0x2bf9 + *(int32_t *)(v1 + 3229 + 4 * v7);
}

// Address range: 0x14b8 - 0x1527
int32_t checkRes(int32_t a1) {
    // 0x14b8
    int32_t v1; // 0x14b8
    __x86_get_pc_thunk_dx(v1);
    int32_t v2; // bp-136, 0x14b8
    int32_t v3; // 0x14b8
    __asm_rep_movsd_memcpy((char *)&v2, (char *)(v3 + 3067), 30);
    int32_t v4 = 0; // 0x1511
    int32_t v5 = 4 * v4; // 0x14ee
    int32_t v6; // bp-4, 0x14b8
    int32_t v7 = *(int32_t *)((int32_t)&v6 - 132 + v5); // 0x14ee
    int32_t result = 0; // 0x1508
    while (v7 == *(int32_t *)(v5 + a1)) {
        // 0x1515
        v4++;
        result = 1;
        if (v4 >= 30) {
            // break -> 0x1520
            break;
        }
        v5 = 4 * v4;
        v7 = *(int32_t *)((int32_t)&v6 - 132 + v5);
        result = 0;
    }
    // 0x1520
    return result;
}

// Address range: 0x1527 - 0x1692
int32_t checkPassword(int32_t a1) {
    // 0x1527
    int32_t v1; // 0x1527
    __x86_get_pc_thunk_ax(v1);
    int32_t v2 = 5; // bp-136, 0x1541
    int32_t v3; // bp-140, 0x1527
    process(a1, &v2, &v3);
    prepare(a1, &v3);
    verify(a1);
    format(a1, &v3);
    return checkRes(v3) == 1;
}

// Address range: 0x1692 - 0x17c1
int main(int argc, char ** argv) {
    // 0x1692
    int32_t v1; // 0x1692
    __x86_get_pc_thunk_bx((int32_t)&v1);
    function_10b0();
    function_10b0();
    int32_t v2; // 0x1692
    function_1050(v2 + 2736);
    function_1060();
    int32_t v3; // bp-64, 0x1692
    int32_t v4 = &v3; // 0x16f6
    int32_t * v5 = (int32_t *)(v4 - 16);
    for (int32_t i = 0; i < 5; i++) {
        // 0x1702
        *v5 = 46;
        function_10d0(i);
        *v5 = *(int32_t *)*(int32_t *)(v2 + 0x294b);
        function_1060();
    }
    // 0x172d
    *v5 = v2 + 2763;
    function_1050(5);
    *(int32_t *)(v4 - 8) = *(int32_t *)*(int32_t *)(v2 + 0x2947);
    *(int32_t *)(v4 - 12) = 31;
    int32_t v6; // bp-51, 0x1692
    int32_t v7 = &v6; // 0x1750
    *v5 = v7;
    if (function_1080() == 0) {
        // 0x1799
        *v5 = v2 + 2835;
        function_10b0();
        // 0x17b7
        return -1;
    }
    // 0x175d
    *v5 = v7;
    if (checkPassword((int32_t)&g1) != 1) {
        // 0x1785
        *v5 = v2 + 2810;
        function_10b0();
    } else {
        // 0x1771
        *v5 = v2 + 2794;
        function_10b0();
    }
    // 0x17b7
    return 0;
}

// Address range: 0x17c1 - 0x17c5
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x17c1
    return result;
}

// Address range: 0x17c8 - 0x17c9
int32_t _fini(void) {
    // 0x17c8
    int32_t result; // 0x17c8
    return result;
}

// Address range: 0x17ca - 0x17e0
int32_t function_17ca(void) {
    // 0x17ca
    int16_t v1; // 0x17ca
    __asm_sti(v1);
    int32_t v2; // 0x17ca
    return __x86_get_pc_thunk_bx(v2);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.2.0)
// Detected functions: 34
