//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(void);
int32_t __x86_get_pc_thunk_ax(int32_t result);
int32_t __x86_get_pc_thunk_bp(int32_t a1);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(int32_t a1, int32_t a2, int32_t a3);
int32_t _start(void);
int32_t checkPassword(void);
int32_t checkRes(int32_t a1);
int32_t deregister_tm_clones(void);
int32_t format(int32_t a1, int32_t * a2);
int32_t frame_dummy(void);
int32_t function_1002(void);
int32_t function_10e0(int32_t a1);
int32_t function_10e2(void);
int32_t function_10f0(int32_t a1);
int32_t function_10f2(void);
int32_t function_1100(void);
int32_t function_1102(void);
int32_t function_1110(int32_t a1);
int32_t function_1112(void);
int32_t function_1120(void);
int32_t function_1122(void);
int32_t function_1130(int32_t a1);
int32_t function_1132(void);
int32_t function_1140(int32_t a1);
int32_t function_1142(void);
int32_t function_1150(void);
int32_t function_1152(void);
int32_t function_1160(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t function_1162(void);
int32_t function_1170(int32_t a1, int32_t a2);
int32_t function_1172(void);
int32_t function_1180(int32_t a1);
int32_t function_1182(void);
int32_t function_1192(void);
int32_t function_11c6(int32_t a1, int32_t * a2, int32_t a3);
int32_t function_1272(void);
int32_t function_12c2(void);
int32_t function_12cf(int32_t a1, int32_t a2);
int32_t function_1380(int32_t a1);
int32_t function_13e0(int32_t a1, int32_t a2);
int32_t function_1469(int32_t a1);
int32_t function_157b(int32_t a1);
int32_t function_15ee(int32_t a1);
int32_t function_175d(void);
int32_t function_18a2(int32_t a1);
int32_t function_1912(void);
int32_t function_191e(void);
int32_t prepare(int32_t a1, int32_t * a2);
int32_t process(int32_t a1, int32_t * a2, int32_t * a3);
int32_t register_tm_clones(void);
int32_t verify(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int32_t _init(int32_t a1, int32_t a2, int32_t a3) {
    // 0x1000
    int32_t result; // 0x1000
    return result;
}

// Address range: 0x1002 - 0x1024
int32_t function_1002(void) {
    // 0x1002
    int16_t v1; // 0x1002
    __asm_sti(v1);
    int32_t v2; // 0x1002
    __x86_get_pc_thunk_bx(v2);
    return *(int32_t *)(v2 + 0x2fdf);
}

// Address range: 0x10e0 - 0x10e1
int32_t function_10e0(int32_t a1) {
    // 0x10e0
    int32_t result; // 0x10e0
    return result;
}

// Address range: 0x10e2 - 0x10ea
int32_t function_10e2(void) {
    // 0x10e2
    int16_t v1; // 0x10e2
    return __asm_sti(v1);
}

// Address range: 0x10f0 - 0x10f1
int32_t function_10f0(int32_t a1) {
    // 0x10f0
    int32_t result; // 0x10f0
    return result;
}

// Address range: 0x10f2 - 0x10fa
int32_t function_10f2(void) {
    // 0x10f2
    int16_t v1; // 0x10f2
    return __asm_sti(v1);
}

// Address range: 0x1100 - 0x1101
int32_t function_1100(void) {
    // 0x1100
    int32_t result; // 0x1100
    return result;
}

// Address range: 0x1102 - 0x110a
int32_t function_1102(void) {
    // 0x1102
    int16_t v1; // 0x1102
    return __asm_sti(v1);
}

// Address range: 0x1110 - 0x1111
int32_t function_1110(int32_t a1) {
    // 0x1110
    int32_t result; // 0x1110
    return result;
}

// Address range: 0x1112 - 0x111a
int32_t function_1112(void) {
    // 0x1112
    int16_t v1; // 0x1112
    return __asm_sti(v1);
}

// Address range: 0x1120 - 0x1121
int32_t function_1120(void) {
    // 0x1120
    int32_t result; // 0x1120
    return result;
}

// Address range: 0x1122 - 0x112a
int32_t function_1122(void) {
    // 0x1122
    int16_t v1; // 0x1122
    return __asm_sti(v1);
}

// Address range: 0x1130 - 0x1131
int32_t function_1130(int32_t a1) {
    // 0x1130
    int32_t result; // 0x1130
    return result;
}

// Address range: 0x1132 - 0x113a
int32_t function_1132(void) {
    // 0x1132
    int16_t v1; // 0x1132
    return __asm_sti(v1);
}

// Address range: 0x1140 - 0x1141
int32_t function_1140(int32_t a1) {
    // 0x1140
    int32_t result; // 0x1140
    return result;
}

// Address range: 0x1142 - 0x114a
int32_t function_1142(void) {
    // 0x1142
    int16_t v1; // 0x1142
    return __asm_sti(v1);
}

// Address range: 0x1150 - 0x1151
int32_t function_1150(void) {
    // 0x1150
    int32_t result; // 0x1150
    return result;
}

// Address range: 0x1152 - 0x115a
int32_t function_1152(void) {
    // 0x1152
    int16_t v1; // 0x1152
    return __asm_sti(v1);
}

// Address range: 0x1160 - 0x1161
int32_t function_1160(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0x1160
    int32_t result; // 0x1160
    return result;
}

// Address range: 0x1162 - 0x116a
int32_t function_1162(void) {
    // 0x1162
    int16_t v1; // 0x1162
    return __asm_sti(v1);
}

// Address range: 0x1170 - 0x1171
int32_t function_1170(int32_t a1, int32_t a2) {
    // 0x1170
    int32_t result; // 0x1170
    return result;
}

// Address range: 0x1172 - 0x117a
int32_t function_1172(void) {
    // 0x1172
    int16_t v1; // 0x1172
    return __asm_sti(v1);
}

// Address range: 0x1180 - 0x1181
int32_t function_1180(int32_t a1) {
    // 0x1180
    int32_t result; // 0x1180
    return result;
}

// Address range: 0x1182 - 0x118a
int32_t function_1182(void) {
    // 0x1182
    int16_t v1; // 0x1182
    return __asm_sti(v1);
}

// Address range: 0x1190 - 0x1191
int32_t _start(void) {
    // 0x1190
    int32_t result; // 0x1190
    return result;
}

// Address range: 0x1192 - 0x11c6
int32_t function_1192(void) {
    // 0x1192
    int16_t v1; // 0x1192
    int32_t v2 = __asm_sti(v1); // 0x1193
    int32_t v3 = v2; // bp-4, 0x119c
    int32_t v4; // 0x1192
    function_11c6(v4, &v3, v2);
    int32_t v5; // 0x1192
    int32_t v6 = *(int32_t *)(v5 + 0x2e54); // 0x11ba
    int32_t v7; // 0x1192
    function_1160(v6, (int32_t)v1, &v7, v5 + 1788, v5 + 1900);
    return __asm_hlt();
}

// Address range: 0x11c6 - 0x11ca
int32_t function_11c6(int32_t a1, int32_t * a2, int32_t a3) {
    // 0x11c6
    int32_t result; // 0x11c6
    return result;
}

// Address range: 0x11d0 - 0x11d4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x11d0
    int32_t result; // 0x11d0
    return result;
}

// Address range: 0x11e0 - 0x1219
int32_t deregister_tm_clones(void) {
    // 0x11e0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x11e0
    return v1 + 0x2e23;
}

// Address range: 0x1220 - 0x1267
int32_t register_tm_clones(void) {
    // 0x1220
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1270 - 0x1271
int32_t __do_global_dtors_aux(void) {
    // 0x1270
    int32_t result; // 0x1270
    return result;
}

// Address range: 0x1272 - 0x12bb
int32_t function_1272(void) {
    // 0x1272
    int16_t v1; // 0x1272
    __asm_sti(v1);
    int32_t v2; // 0x1272
    int32_t result = __x86_get_pc_thunk_bx(v2); // 0x1278
    char * v3 = (char *)(v2 + 0x2d8b); // 0x1286
    if (*v3 != 0) {
        // 0x12b6
        return result;
    }
    // 0x128f
    if (*(int32_t *)(v2 + 0x2d6b) != 0) {
        // 0x1299
        function_10e0(*(int32_t *)(v2 + 0x2d87));
    }
    int32_t result2 = deregister_tm_clones(); // 0x12aa
    *v3 = 1;
    // 0x12b6
    return result2;
}

// Address range: 0x12c0 - 0x12c1
int32_t frame_dummy(void) {
    // 0x12c0
    int32_t result; // 0x12c0
    return result;
}

// Address range: 0x12c2 - 0x12c9
int32_t function_12c2(void) {
    // 0x12c2
    int16_t v1; // 0x12c2
    __asm_sti(v1);
    return register_tm_clones();
}

// Address range: 0x12c9 - 0x12cd
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x12c9
    int32_t result; // 0x12c9
    return result;
}

// Address range: 0x12cd - 0x12ce
int32_t process(int32_t a1, int32_t * a2, int32_t * a3) {
    // 0x12cd
    int32_t result; // 0x12cd
    return result;
}

// Address range: 0x12cf - 0x137e
int32_t function_12cf(int32_t a1, int32_t a2) {
    // 0x12cf
    int16_t v1; // 0x12cf
    __asm_sti(v1);
    int32_t v2; // 0x12cf
    __x86_get_pc_thunk_ax(v2);
    int32_t v3 = function_1140(120); // 0x12f0
    int32_t * v4 = (int32_t *)a2; // 0x12fd
    *v4 = v3;
    *(int32_t *)v3 = 0;
    int32_t v5 = 1; // 0x131b
    *(int32_t *)(4 * v5 + *v4) = 0;
    v5++;
    int32_t v6 = 0; // 0x1323
    while (v5 != 30) {
        // 0x1308
        *(int32_t *)(4 * v5 + *v4) = 0;
        v5++;
        v6 = 0;
    }
    int32_t v7 = 4 * v6; // 0x135b
    int32_t * v8 = (int32_t *)(v7 + a1); // 0x1367
    int32_t v9 = *v8; // 0x1367
    int32_t result = v9; // 0x136b
    int32_t * v10; // 0x133b
    int32_t v11; // 0x1353
    if (v9 != 0) {
        v10 = (int32_t *)(*v4 + v7);
        *v10 = *v10 + 1;
        v11 = *v8 - 1;
        *v8 = v11;
        result = v11;
        while (v11 != 0) {
            // 0x132e
            v10 = (int32_t *)(*v4 + v7);
            *v10 = *v10 + 1;
            v11 = *v8 - 1;
            *v8 = v11;
            result = v11;
        }
    }
    int32_t v12 = v6 + 1; // 0x136d
    v6 = v12;
    while (v12 != 30) {
        // 0x1358
        v7 = 4 * v6;
        v8 = (int32_t *)(v7 + a1);
        v9 = *v8;
        result = v9;
        if (v9 != 0) {
            v10 = (int32_t *)(*v4 + v7);
            *v10 = *v10 + 1;
            v11 = *v8 - 1;
            *v8 = v11;
            result = v11;
            while (v11 != 0) {
                // 0x132e
                v10 = (int32_t *)(*v4 + v7);
                *v10 = *v10 + 1;
                v11 = *v8 - 1;
                *v8 = v11;
                result = v11;
            }
        }
        // 0x136d
        v12 = v6 + 1;
        v6 = v12;
    }
    // 0x1377
    return result;
}

// Address range: 0x137e - 0x137f
int32_t verify(int32_t a1) {
    // 0x137e
    int32_t result; // 0x137e
    return result;
}

// Address range: 0x1380 - 0x13de
int32_t function_1380(int32_t a1) {
    // 0x1380
    int16_t v1; // 0x1380
    __asm_sti(v1);
    int32_t v2; // 0x1380
    __x86_get_pc_thunk_ax(v2);
    int32_t v3 = 5;
    for (int32_t i = 0; i < 25; i++) {
        uint32_t v4 = v3;
        char v5 = *(char *)(i + a1); // 0x13b1
        v3 = v5 != 45 ? v4 : v4 % 4;
    }
    // 0x13ca
    return v3 != 92;
}

// Address range: 0x13de - 0x13df
int32_t format(int32_t a1, int32_t * a2) {
    // 0x13de
    int32_t result; // 0x13de
    return result;
}

// Address range: 0x13e0 - 0x1467
int32_t function_13e0(int32_t a1, int32_t a2) {
    // 0x13e0
    int16_t v1; // 0x13e0
    __asm_sti(v1);
    int32_t v2; // 0x13e0
    __x86_get_pc_thunk_bx(v2);
    int32_t v3 = function_1140(120); // 0x1401
    for (int32_t i = 0; i < 30; i++) {
        int32_t * v4 = (int32_t *)(*(int32_t *)a2 + 4 * i); // 0x1430
        *v4 = (int32_t)*(char *)(i + a1) << *v4 % 32;
    }
    // 0x1451
    return function_1110(v3);
}

// Address range: 0x1467 - 0x1468
int32_t prepare(int32_t a1, int32_t * a2) {
    // 0x1467
    int32_t result; // 0x1467
    return result;
}

// Address range: 0x1469 - 0x1579
int32_t function_1469(int32_t a1) {
    // 0x1469
    int16_t v1; // 0x1469
    __asm_sti(v1);
    int32_t v2; // 0x1469
    __x86_get_pc_thunk_bx(v2);
    int32_t v3 = function_1170(v2 + 2987, v2 + 2985); // 0x1495
    int32_t v4; // bp-30, 0x1469
    int32_t v5 = &v4; // 0x149a
    int32_t v6 = 0; // 0x1564
    char v7 = *(char *)(v6 + a1); // 0x14b4
    uint32_t v8 = (int32_t)v7 - 99; // 0x14ba
    while (v7 != 125 && v8 >= 26) {
        // 0x154d
        *(int32_t *)(v5 - 4) = v3;
        *(int32_t *)(v5 - 8) = 5;
        *(int32_t *)(v5 - 12) = 1;
        *(int32_t *)(v5 - 16) = v2 + 3030;
        int32_t result = function_1130(v6); // 0x155b
        v6++;
        if (v6 >= 30) {
            // 0x1572
            return result;
        }
        v7 = *(char *)(v6 + a1);
        v8 = (int32_t)v7 - 99;
    }
    // 0x14c6
    return v2 + 0x2b39 + *(int32_t *)(v2 + 3037 + 4 * v8);
}

// Address range: 0x1579 - 0x157a
int32_t checkRes(int32_t a1) {
    // 0x1579
    int32_t result; // 0x1579
    return result;
}

// Address range: 0x157b - 0x15ec
int32_t function_157b(int32_t a1) {
    // 0x157b
    int16_t v1; // 0x157b
    __asm_sti(v1);
    int32_t v2; // 0x157b
    __x86_get_pc_thunk_dx(v2);
    int32_t v3; // bp-138, 0x157b
    int32_t v4; // 0x157b
    __asm_rep_movsd_memcpy((char *)&v3, (char *)(v4 + 2870), 30);
    int32_t v5 = 0; // 0x15d6
    int32_t v6 = 4 * v5; // 0x15b3
    int32_t v7; // bp-6, 0x157b
    int32_t v8 = *(int32_t *)((int32_t)&v7 - 132 + v6); // 0x15b3
    int32_t result = 0; // 0x15cd
    while (v8 == *(int32_t *)(v6 + a1)) {
        // 0x15da
        v5++;
        result = 1;
        if (v5 >= 30) {
            // break -> 0x15e5
            break;
        }
        v6 = 4 * v5;
        v8 = *(int32_t *)((int32_t)&v7 - 132 + v6);
        result = 0;
    }
    // 0x15e5
    return result;
}

// Address range: 0x15ec - 0x15ed
int32_t checkPassword(void) {
    // 0x15ec
    int32_t result; // 0x15ec
    return result;
}

// Address range: 0x15ee - 0x175b
int32_t function_15ee(int32_t a1) {
    // 0x15ee
    int16_t v1; // 0x15ee
    __asm_sti(v1);
    int32_t v2; // 0x15ee
    __x86_get_pc_thunk_ax(v2);
    int32_t v3 = 5; // bp-138, 0x160a
    int32_t v4; // bp-142, 0x15ee
    process(a1, &v3, &v4);
    prepare(a1, &v4);
    verify(a1);
    format(a1, &v4);
    return checkRes(v4) == 1;
}

// Address range: 0x175b - 0x175c
int main(int argc, char ** argv) {
    // 0x175b
    int32_t result; // 0x175b
    return result;
}

// Address range: 0x175d - 0x188e
int32_t function_175d(void) {
    // 0x175d
    int16_t v1; // 0x175d
    __asm_sti(v1);
    int32_t v2; // 0x175d
    __x86_get_pc_thunk_bx((int32_t)&v2);
    function_1150();
    function_1150();
    int32_t v3; // 0x175d
    function_10f0(v3 + 2531);
    function_1100();
    int32_t v4; // bp-80, 0x175d
    int32_t v5 = &v4; // 0x17c3
    int32_t * v6 = (int32_t *)(v5 - 16);
    for (int32_t i = 0; i < 5; i++) {
        // 0x17cf
        *v6 = 46;
        function_1180(i);
        *v6 = *(int32_t *)*(int32_t *)(v3 + 0x287e);
        function_1100();
    }
    // 0x17fa
    *v6 = v3 + 2558;
    function_10f0(5);
    *(int32_t *)(v5 - 8) = *(int32_t *)*(int32_t *)(v3 + 0x287a);
    *(int32_t *)(v5 - 12) = 31;
    int32_t v7; // bp-67, 0x175d
    int32_t v8 = &v7; // 0x181d
    *v6 = v8;
    if (function_1120() == 0) {
        // 0x1866
        *v6 = v3 + 2630;
        function_1150();
        // 0x1884
        return -1;
    }
    // 0x182a
    *v6 = v8;
    if (checkPassword() != 1) {
        // 0x1852
        *v6 = v3 + 2605;
        function_1150();
    } else {
        // 0x183e
        *v6 = v3 + 2589;
        function_1150();
    }
    // 0x1884
    return 0;
}

// Address range: 0x188e - 0x1892
int32_t __x86_get_pc_thunk_ax(int32_t result) {
    // 0x188e
    return result;
}

// Address range: 0x18a0 - 0x18a1
int32_t __libc_csu_init(void) {
    // 0x18a0
    int32_t result; // 0x18a0
    return result;
}

// Address range: 0x18a2 - 0x1905
int32_t function_18a2(int32_t a1) {
    // 0x18fd
    int16_t v1; // 0x18a2
    __asm_sti(v1);
    int32_t v2; // 0x18a2
    __x86_get_pc_thunk_bp(v2);
    int32_t v3; // bp-30, 0x18a2
    int32_t v4 = &v3; // 0x18b3
    int32_t v5; // 0x18a2
    int32_t v6; // 0x18a2
    int32_t v7; // 0x18a2
    _init(v7, v6, v5);
    *(int32_t *)(v4 - 8) = a1;
    *(int32_t *)(v4 - 12) = *(int32_t *)(v4 + 36);
    *(int32_t *)(v4 - 16) = *(int32_t *)(v4 + 32);
    return v2 + 0x2606;
}

// Address range: 0x1910 - 0x1911
int32_t __libc_csu_fini(void) {
    // 0x1910
    int32_t result; // 0x1910
    return result;
}

// Address range: 0x1912 - 0x1915
int32_t function_1912(void) {
    // 0x1912
    int16_t v1; // 0x1912
    return __asm_sti(v1);
}

// Address range: 0x1915 - 0x1919
int32_t __x86_get_pc_thunk_bp(int32_t a1) {
    // 0x1915
    int32_t result; // 0x1915
    return result;
}

// Address range: 0x191c - 0x191d
int32_t _fini(void) {
    // 0x191c
    int32_t result; // 0x191c
    return result;
}

// Address range: 0x191e - 0x1934
int32_t function_191e(void) {
    // 0x191e
    int16_t v1; // 0x191e
    __asm_sti(v1);
    int32_t v2; // 0x191e
    return __x86_get_pc_thunk_bx(v2);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.4.0)
// Detected functions: 57
